<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

<img src="Images/Img11.jpg">

	<style>
body {
  background-color: lightblue;
}

h1 {
  color: maroon;
  margin-left: 40px;
} 
</style>
</head>


	<title></title>

</head>
<body>
	
	<h1>Agra</h1>
	<p>Jammu & Kashmir, a piece of heaven on earth, is the 19th largest state in India and it is located mostly all in the Himalayan mountains. It is also the only state in India with a Muslim-majority population. J&K consists of three main regions – Jammu, the Kashmir Valley and Ladakh. Between the three, the state offers beautiful verdant mountains and valleys, religious shrines and remote mountains. The people here are warm and hospitable, and they will welcome you into their land and homes easily. Each of these regions has its own culture, and this is evident in their daily lives and also their lifestyle. Whatever your reason for visiting J&K, whether it is to enjoy the beauty, or test your limits while trekking the mountains, or simply to discover serenity and peace, J&K will offer you several reasons to keep coming back for more.</p>
	<p>Post India's independence, Agra has been a part of Uttar Pradesh and has gradually developed into an industrial city, with a significant contribution to Uttar Pradesh's economy. The city is now a popular tourist destination and hosts tourists from across the world.[45] The Taj Mahal and Agra Fort received UNESCO World Heritage Sites status in 1983.[46][47] The Taj Mahal witnesses tourists, photographers, historians and archaeologists in massive numbers all around the year. The Taj Mahal has become a symbol of India and its soft power.[48][49] Post Independence, Taj Mahal has been visited by world leaders like US Presidents Dwight D. Eisenhower (1959), Bill Clinton (2000), and Donald Trump (2020). Queen Elizabeth II of the United Kingdom had visited Taj Mahal in 1961 on her India visit. Taj Mahal has also been visited by Russian President Vladimir Putin (1999), Chinese President Hu Jintao (2006), Israeli Prime Minister Benjamin Netanyahu (2018) and Canadian Prime Minister Justin Trudeau (2018).[50] Agra is the birthplace of the now extinct religion known as Din-i-Ilahi, which was founded by Akbar[51] and also of the Radhaswami Faith,[citation needed] which has around two million followers worldwide. Agra is included on the Golden Triangle tourist circuit, along with Delhi and Jaipur;[52] and the Uttar Pradesh Heritage Arc, a tourist circuit of Uttar Pradesh, along with Lucknow and Varanasi.</p>
	<p>The decline of the Mughal empire caused the emergence of several regional kingdoms, and in the late 18th century the control of the city fell successively to the Jats, the Marathas, the Mughals, the ruler of Gwalior, and finally the British East India Company.[33] The Jats of Bharatpur, waged many wars against the Mughal Delhi and in the 17th and 18th century carried out numerous campaigns in Mughal territories including Agra.[34] After the decline of the Mughal Empire, the city came under the influence of another post-Mughal Empire power, the Marathas, before falling into the hands of the British East India Company in 1803.[33] In the years 1834–1836, Agra was the capital of the short-lived Presidency of Agra, administered by a Governor. It was then the capital of the North-Western Province from 1836 to 1868, governed by a Lieutenant-Governor.[35][36] Agra was one of the centres of the Indian rebellion of 1857.[37]

During the Indian rebellion of 1857, when East India Company rule across many parts of India was threatened, the news of the mutiny at Meerut reached Agra on 14 May. On 30 May some companies of the 44th and 67th Native Infantry sent to Mathura to bring in the treasury mutinied and carried off the treasury to the rebels in Delhi. With the fear of the rebellion spreading to Agra as well, the rest of these native infantry battalions, which were part of the garrison at Agra, were successfully disarmed by the British on 31 May.[13][38] However, when the Gwalior contingent mutinied on 15 June, all other native units followed. On 2 July the rebel force of the Nimach and Nasirabad contingents reached Fatehpur Sikri. Fearing advance of the mutineers to Agra, some 6000 Europeans and associated people moved into the Agra Fort for safety on 3 July. On 5 July, the British force stationed there attempted to attack an approaching force of Mutineers, but was defeated, and the British retreated back into the fort.[13] The Lieutenant-Governor, J.R. Colvin, died there, and was later buried in front of the Diwan-i-am.[39][13] The mutineers, however, moved over to Delhi, it being a more important attraction for the rebels. Despite an uprising by a mob and extreme disorder in the city, the British managed to restore partial order by 8 July.[13] Delhi, in turn, fell to the British in September, following which an infantry brigade led by Brigadier Edward Greathed arrived in Agra on 11 October without any opposition from rebels. But shortly after their arrival another force of mutineers attacked the brigade by surprise, but was defeated and routed. This minor victory for the British was named the Battle of Agra.[40][13] It is to be said that, the uprising in Agra was relatively minor compared to Delhi, Jhansi, Meerut and other major rebellious cities and regions.[39] After this British rule was again secured, and the British Raj ruled the city till the independence of India in 1947.[41] The capital of the North Western Provinces was shifted from Agra to Allahabad in 1868. Gradually, Agra declined to the position of a mere provincial town, and its prosperity declined:[36]

But in the economy of the administration of British India Agra is nothing more than a district town; its size, proportions and manifold activities have come down to its present requirements, and continued life in this city does not come above the average of that monotonous muffasil life in India which has been so often and so vividly described by many gifted Anglo-Indian writers. Agra has become of late years a large railway centre, and its commercial prosperity seems to be reviving.

— Agra by 1892, as described by S.C. Mukerji, Traveller's Guide to Agra, pp 55-56
Agra's role in the Indian Independence movement is not well documented.[42] However, in the years between the mutiny and independence Agra was a major centre of Hindi and Urdu journalism.[citation needed] Paliwal park(formerly Hewitt park) in Agra is named after S.K.D Paliwal,[43] who brought out the Hindi daily Sainik.</p>
<p>The Taj Mahal has faced significant damage due to air pollution and sewage discharge into the nearby Yamuna river.[74] The white-marble Taj Mahal is turning yellow and green because of filthy air in the world's eighth-most polluted city. The Taj Mahal flanks the garbage-strewn Yamuna river and is often enveloped by dust and smog from smokestacks and vehicles.[75]

The Yamuna River is one of the most polluted rivers in the world.[76] Agra is the second largest contributor to River Yamuna's pollution, after Delhi.[77] The river's pollution has caused several problems for the Taj Mahal such as 'Attacks by Bugs and their Green Slime',[78] foul stench[79] and corrosion of Taj Mahal's foundation.[79] The river has as many as 90 nalas or drains opening into it. Though the municipality has claimed to stop 40 of these drains, the bigger ones, Bhairon, Mantola, Balkeshwar nalas continue to discharge huge quantities of untreated waste water without any check.[80] Activists say that the Yamuna river bed between Itmad-ud-Daula and the Taj Mahal has become a dumping ground for pollutants. Polythene, plastic waste, leather cuttings from shoe factories, construction material, are all thrown into the river.[80]

Less than 7% of the Agra district is under forest cover.[81] The only major wildlife sanctuary near Agra is Keetham Lake, also known as Sur Sarovar Bird Sanctuary. The lake has nearly two dozen varieties of migratory and resident birds.[82] Within the Sur Sarovar Bird Sanctuary is the Agra Bear Rescue Facility, which is India's first sanctuary for 'dancing' bears. Operated by Wildlife SOS, Free the Bears Fund and others, the facility has rehabilitate over 620 sloth bears, which were exploited by a nomadic tribe known as the Kalandars as 'dancing bears', despite the practice being illegal since 1972.The Taj Mahal has faced significant damage due to air pollution and sewage discharge into the nearby Yamuna river.[74] The white-marble Taj Mahal is turning yellow and green because of filthy air in the world's eighth-most polluted city. The Taj Mahal flanks the garbage-strewn Yamuna river and is often enveloped by dust and smog from smokestacks and vehicles.[75]

The Yamuna River is one of the most polluted rivers in the world.[76] Agra is the second largest contributor to River Yamuna's pollution, after Delhi.[77] The river's pollution has caused several problems for the Taj Mahal such as 'Attacks by Bugs and their Green Slime',[78] foul stench[79] and corrosion of Taj Mahal's foundation.[79] The river has as many as 90 nalas or drains opening into it. Though the municipality has claimed to stop 40 of these drains, the bigger ones, Bhairon, Mantola, Balkeshwar nalas continue to discharge huge quantities of untreated waste water without any check.[80] Activists say that the Yamuna river bed between Itmad-ud-Daula and the Taj Mahal has become a dumping ground for pollutants. Polythene, plastic waste, leather cuttings from shoe factories, construction material, are all thrown into the river.[80]

Less than 7% of the Agra district is under forest cover.[81] The only major wildlife sanctuary near Agra is Keetham Lake, also known as Sur Sarovar Bird Sanctuary. The lake has nearly two dozen varieties of migratory and resident birds.[82] Within the Sur Sarovar Bird Sanctuary is the Agra Bear Rescue Facility, which is India's first sanctuary for 'dancing' bears. Operated by Wildlife SOS, Free the Bears Fund and others, the facility has rehabilitate over 620 sloth bears, which were exploited by a nomadic tribe known as the Kalandars as 'dancing bears', despite the practice being illegal since 1972.The Taj Mahal has faced significant damage due to air pollution and sewage discharge into the nearby Yamuna river.[74] The white-marble Taj Mahal is turning yellow and green because of filthy air in the world's eighth-most polluted city. The Taj Mahal flanks the garbage-strewn Yamuna river and is often enveloped by dust and smog from smokestacks and vehicles.[75]

The Yamuna River is one of the most polluted rivers in the world.[76] Agra is the second largest contributor to River Yamuna's pollution, after Delhi.[77] The river's pollution has caused several problems for the Taj Mahal such as 'Attacks by Bugs and their Green Slime',[78] foul stench[79] and corrosion of Taj Mahal's foundation.[79] The river has as many as 90 nalas or drains opening into it. Though the municipality has claimed to stop 40 of these drains, the bigger ones, Bhairon, Mantola, Balkeshwar nalas continue to discharge huge quantities of untreated waste water without any check.[80] Activists say that the Yamuna river bed between Itmad-ud-Daula and the Taj Mahal has become a dumping ground for pollutants. Polythene, plastic waste, leather cuttings from shoe factories, construction material, are all thrown into the river.[80]

Less than 7% of the Agra district is under forest cover.[81] The only major wildlife sanctuary near Agra is Keetham Lake, also known as Sur Sarovar Bird Sanctuary. The lake has nearly two dozen varieties of migratory and resident birds.[82] Within the Sur Sarovar Bird Sanctuary is the Agra Bear Rescue Facility, which is India's first sanctuary for 'dancing' bears. Operated by Wildlife SOS, Free the Bears Fund and others, the facility has rehabilitate over 620 sloth bears, which were exploited by a nomadic tribe known as the Kalandars as 'dancing bears', despite the practice being illegal since 1972.The Taj Mahal has faced significant damage due to air pollution and sewage discharge into the nearby Yamuna river.[74] The white-marble Taj Mahal is turning yellow and green because of filthy air in the world's eighth-most polluted city. The Taj Mahal flanks the garbage-strewn Yamuna river and is often enveloped by dust and smog from smokestacks and vehicles.[75]

The Yamuna River is one of the most polluted rivers in the world.[76] Agra is the second largest contributor to River Yamuna's pollution, after Delhi.[77] The river's pollution has caused several problems for the Taj Mahal such as 'Attacks by Bugs and their Green Slime',[78] foul stench[79] and corrosion of Taj Mahal's foundation.[79] The river has as many as 90 nalas or drains opening into it. Though the municipality has claimed to stop 40 of these drains, the bigger ones, Bhairon, Mantola, Balkeshwar nalas continue to discharge huge quantities of untreated waste water without any check.[80] Activists say that the Yamuna river bed between Itmad-ud-Daula and the Taj Mahal has become a dumping ground for pollutants. Polythene, plastic waste, leather cuttings from shoe factories, construction material, are all thrown into the river.[80]

Less than 7% of the Agra district is under forest cover.[81] The only major wildlife sanctuary near Agra is Keetham Lake, also known as Sur Sarovar Bird Sanctuary. The lake has nearly two dozen varieties of migratory and resident birds.[82] Within the Sur Sarovar Bird Sanctuary is the Agra Bear Rescue Facility, which is India's first sanctuary for 'dancing' bears. Operated by Wildlife SOS, Free the Bears Fund and others, the facility has rehabilitate over 620 sloth bears, which were exploited by a nomadic tribe known as the Kalandars as 'dancing bears', despite the practice being illegal since 1972.The Taj Mahal has faced significant damage due to air pollution and sewage discharge into the nearby Yamuna river.[74] The white-marble Taj Mahal is turning yellow and green because of filthy air in the world's eighth-most polluted city. The Taj Mahal flanks the garbage-strewn Yamuna river and is often enveloped by dust and smog from smokestacks and vehicles.[75]

The Yamuna River is one of the most polluted rivers in the world.[76] Agra is the second largest contributor to River Yamuna's pollution, after Delhi.[77] The river's pollution has caused several problems for the Taj Mahal such as 'Attacks by Bugs and their Green Slime',[78] foul stench[79] and corrosion of Taj Mahal's foundation.[79] The river has as many as 90 nalas or drains opening into it. Though the municipality has claimed to stop 40 of these drains, the bigger ones, Bhairon, Mantola, Balkeshwar nalas continue to discharge huge quantities of untreated waste water without any check.[80] Activists say that the Yamuna river bed between Itmad-ud-Daula and the Taj Mahal has become a dumping ground for pollutants. Polythene, plastic waste, leather cuttings from shoe factories, construction material, are all thrown into the river.[80]

Less than 7% of the Agra district is under forest cover.[81] The only major wildlife sanctuary near Agra is Keetham Lake, also known as Sur Sarovar Bird Sanctuary. The lake has nearly two dozen varieties of migratory and resident birds.[82] Within the Sur Sarovar Bird Sanctuary is the Agra Bear Rescue Facility, which is India's first sanctuary for 'dancing' bears. Operated by Wildlife SOS, Free the Bears Fund and others, the facility has rehabilitate over 620 sloth bears, which were exploited by a nomadic tribe known as the Kalandars as 'dancing bears', despite the practice being illegal since 1972.The Taj Mahal has faced significant damage due to air pollution and sewage discharge into the nearby Yamuna river.[74] The white-marble Taj Mahal is turning yellow and green because of filthy air in the world's eighth-most polluted city. The Taj Mahal flanks the garbage-strewn Yamuna river and is often enveloped by dust and smog from smokestacks and vehicles.[75]

The Yamuna River is one of the most polluted rivers in the world.[76] Agra is the second largest contributor to River Yamuna's pollution, after Delhi.[77] The river's pollution has caused several problems for the Taj Mahal such as 'Attacks by Bugs and their Green Slime',[78] foul stench[79] and corrosion of Taj Mahal's foundation.[79] The river has as many as 90 nalas or drains opening into it. Though the municipality has claimed to stop 40 of these drains, the bigger ones, Bhairon, Mantola, Balkeshwar nalas continue to discharge huge quantities of untreated waste water without any check.[80] Activists say that the Yamuna river bed between Itmad-ud-Daula and the Taj Mahal has become a dumping ground for pollutants. Polythene, plastic waste, leather cuttings from shoe factories, construction material, are all thrown into the river.[80]

Less than 7% of the Agra district is under forest cover.[81] The only major wildlife sanctuary near Agra is Keetham Lake, also known as Sur Sarovar Bird Sanctuary. The lake has nearly two dozen varieties of migratory and resident birds.[82] Within the Sur Sarovar Bird Sanctuary is the Agra Bear Rescue Facility, which is India's first sanctuary for 'dancing' bears. Operated by Wildlife SOS, Free the Bears Fund and others, the facility has rehabilitate over 620 sloth bears, which were exploited by a nomadic tribe known as the Kalandars as 'dancing bears', despite the practice being illegal since 1972.The Taj Mahal has faced significant damage due to air pollution and sewage discharge into the nearby Yamuna river.[74] The white-marble Taj Mahal is turning yellow and green because of filthy air in the world's eighth-most polluted city. The Taj Mahal flanks the garbage-strewn Yamuna river and is often enveloped by dust and smog from smokestacks and vehicles.[75]

The Yamuna River is one of the most polluted rivers in the world.[76] Agra is the second largest contributor to River Yamuna's pollution, after Delhi.[77] The river's pollution has caused several problems for the Taj Mahal such as 'Attacks by Bugs and their Green Slime',[78] foul stench[79] and corrosion of Taj Mahal's foundation.[79] The river has as many as 90 nalas or drains opening into it. Though the municipality has claimed to stop 40 of these drains, the bigger ones, Bhairon, Mantola, Balkeshwar nalas continue to discharge huge quantities of untreated waste water without any check.[80] Activists say that the Yamuna river bed between Itmad-ud-Daula and the Taj Mahal has become a dumping ground for pollutants. Polythene, plastic waste, leather cuttings from shoe factories, construction material, are all thrown into the river.[80]

Less than 7% of the Agra district is under forest cover.[81] The only major wildlife sanctuary near Agra is Keetham Lake, also known as Sur Sarovar Bird Sanctuary. The lake has nearly two dozen varieties of migratory and resident birds.[82] Within the Sur Sarovar Bird Sanctuary is the Agra Bear Rescue Facility, which is India's first sanctuary for 'dancing' bears. Operated by Wildlife SOS, Free the Bears Fund and others, the facility has rehabilitate over 620 sloth bears, which were exploited by a nomadic tribe known as the Kalandars as 'dancing bears', despite the practice being illegal since 1972.The Taj Mahal has faced significant damage due to air pollution and sewage discharge into the nearby Yamuna river.[74] The white-marble Taj Mahal is turning yellow and green because of filthy air in the world's eighth-most polluted city. The Taj Mahal flanks the garbage-strewn Yamuna river and is often enveloped by dust and smog from smokestacks and vehicles.[75]

The Yamuna River is one of the most polluted rivers in the world.[76] Agra is the second largest contributor to River Yamuna's pollution, after Delhi.[77] The river's pollution has caused several problems for the Taj Mahal such as 'Attacks by Bugs and their Green Slime',[78] foul stench[79] and corrosion of Taj Mahal's foundation.[79] The river has as many as 90 nalas or drains opening into it. Though the municipality has claimed to stop 40 of these drains, the bigger ones, Bhairon, Mantola, Balkeshwar nalas continue to discharge huge quantities of untreated waste water without any check.[80] Activists say that the Yamuna river bed between Itmad-ud-Daula and the Taj Mahal has become a dumping ground for pollutants. Polythene, plastic waste, leather cuttings from shoe factories, construction material, are all thrown into the river.[80]

Less than 7% of the Agra district is under forest cover.[81] The only major wildlife sanctuary near Agra is Keetham Lake, also known as Sur Sarovar Bird Sanctuary. The lake has nearly two dozen varieties of migratory and resident birds.[82] Within the Sur Sarovar Bird Sanctuary is the Agra Bear Rescue Facility, which is India's first sanctuary for 'dancing' bears. Operated by Wildlife SOS, Free the Bears Fund and others, the facility has rehabilitate over 620 sloth bears, which were exploited by a nomadic tribe known as the Kalandars as 'dancing bears', despite the practice being illegal since 1972.</p>

</body>
</html>