<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

<img src="Images/Img9.jpg">

	<style>
body {
  background-color: lightblue;
}

h1 {
  color: maroon;
  margin-left: 40px;
} 
</style>
</head>


	<title></title>

</head>
<body>
	<h1>Kashmir</h1>
	<p>Jammu & Kashmir, a piece of heaven on earth, is the 19th largest state in India and it is located mostly all in the Himalayan mountains. It is also the only state in India with a Muslim-majority population. J&K consists of three main regions – Jammu, the Kashmir Valley and Ladakh. Between the three, the state offers beautiful verdant mountains and valleys, religious shrines and remote mountains. The people here are warm and hospitable, and they will welcome you into their land and homes easily. Each of these regions has its own culture, and this is evident in their daily lives and also their lifestyle. Whatever your reason for visiting J&K, whether it is to enjoy the beauty, or test your limits while trekking the mountains, or simply to discover serenity and peace, J&K will offer you several reasons to keep coming back for more. Pahalgam (Hindustani pronunciation: [pɛhɛlɡaːm]), known as Pahalgom (Kashmiri pronunciation: [pəhəlʲɡoːm]; lit. 'village of shepherds' in Kashmiri)[14] is a town and a notified area committee, near Anantnag city in the Anantnag district of the Indian-administered union territory of Jammu and Kashmir.[15][16][17][18][19] It is a popular tourist destination and hill station. Its lush green meadows and pristine waters attract thousands of tourists from all over the world each year.[20] It is located 45 kilometres (28 mi) from Anantnag on the banks of Lidder River at an altitude of 7,200 feet (2,200 m). Pahalgam is the headquarters of one of the eleven tehsils of Anantnag district.

Pahalgam is associated with the annual pilgrimage to the shrine Amarnath Yatra. Chandanwari, located 16 kilometres (9.9 mi) from Pahalgam. The town is the starting point of the yatra that takes place every year in the months of July–August, receiving hundreds of thousands of tourists. Because of its religious significance and role as a base camp, the town attracts 70% of visitors to the valley. This flood of tourists overwhelms some of the local infrastructure, especially waste management in the town. This section is an excerpt from Sonamarg § Tourism.[edit]
Sonamarg provides trekking routes leading to Vishansar Lake, Krishansar Lake, Gangabal Lake and Gadsar Lake in the Himalayas, which are stocked with snowtrout and brown trout. The Sind River meanders here and abounds with trout and mahseer. Ponies can be hired for the trip up to Thajiwas glacier, a major attraction during the summer months. The Yatra to the nearby Amarnath Temple begins in Sonamarg.

Baltal, 15 km east of Sonamarg, is a valley that lies at the foot of the Zoji La pass. Trekkers can also reach the city of Leh—known as "the rooftop of the world"—by crossing over the Zoji La.

The Jammu and Kashmir tourism department organizes river rafting tournaments at Sonamarg throughout the year, which has recently seen the participation of teams from abroad. Verinag (/ˈveɪriːnɑːɡ/ is a town named after and famous for the Verinag spring and Mughal garden, near Anantnag city in Anantnag district of the union territory of Jammu and Kashmir, India. It is a notified area committee with tehsil status (Shahabad Bala Verinag) and is about 26 kilometers away from Anantnag and approximately 78 kilometres south-east from Srinagar which is the summer capital of the union territory of Jammu and Kashmir. Verinag is also the first tourist spot of Kashmir Valley when travelling by road from Jammu, the winter capital of the union territory of Jammu and Kashmir towards Srinagar. There is an octagonal stone basin at Verinag Spring and an arcade surrounding it which were built by Mughal emperor Jahangir in 1620 A.D. Later, a beautiful garden next to this spring, was laid out by his son Shah Jahan. This spring is known to never dry up or overflow. Verinag Spring is also the major source of river Jhelum. Verinag Spring and Mughal Arcade surrounding it is officially recognized by Archaeological Survey of India as a Monument of National Importance.

Verinag spring is the main source of River Jehlum, (vyeth in local Kashmiri language) which flows throughout the valley of Kashmir and finally enters into Pakistan-administered Kashmir. Pahalgam (Hindustani pronunciation: [pɛhɛlɡaːm]), known as Pahalgom (Kashmiri pronunciation: [pəhəlʲɡoːm]; lit. 'village of shepherds' in Kashmiri)[14] is a town and a notified area committee, near Anantnag city in the Anantnag district of the Indian-administered union territory of Jammu and Kashmir.[15][16][17][18][19] It is a popular tourist destination and hill station. Its lush green meadows and pristine waters attract thousands of tourists from all over the world each year.[20] It is located 45 kilometres (28 mi) from Anantnag on the banks of Lidder River at an altitude of 7,200 feet (2,200 m). Pahalgam is the headquarters of one of the eleven tehsils of Anantnag district.

Pahalgam is associated with the annual pilgrimage to the shrine Amarnath Yatra. Chandanwari, located 16 kilometres (9.9 mi) from Pahalgam. The town is the starting point of the yatra that takes place every year in the months of July–August, receiving hundreds of thousands of tourists. Because of its religious significance and role as a base camp, the town attracts 70% of visitors to the valley. This flood of tourists overwhelms some of the local infrastructure, especially waste management in the town. This section is an excerpt from Sonamarg § Tourism.[edit]
Sonamarg provides trekking routes leading to Vishansar Lake, Krishansar Lake, Gangabal Lake and Gadsar Lake in the Himalayas, which are stocked with snowtrout and brown trout. The Sind River meanders here and abounds with trout and mahseer. Ponies can be hired for the trip up to Thajiwas glacier, a major attraction during the summer months. The Yatra to the nearby Amarnath Temple begins in Sonamarg.

Baltal, 15 km east of Sonamarg, is a valley that lies at the foot of the Zoji La pass. Trekkers can also reach the city of Leh—known as "the rooftop of the world"—by crossing over the Zoji La.

The Jammu and Kashmir tourism department organizes river rafting tournaments at Sonamarg throughout the year, which has recently seen the participation of teams from abroad. Verinag (/ˈveɪriːnɑːɡ/ is a town named after and famous for the Verinag spring and Mughal garden, near Anantnag city in Anantnag district of the union territory of Jammu and Kashmir, India. It is a notified area committee with tehsil status (Shahabad Bala Verinag) and is about 26 kilometers away from Anantnag and approximately 78 kilometres south-east from Srinagar which is the summer capital of the union territory of Jammu and Kashmir. Verinag is also the first tourist spot of Kashmir Valley when travelling by road from Jammu, the winter capital of the union territory of Jammu and Kashmir towards Srinagar. There is an octagonal stone basin at Verinag Spring and an arcade surrounding it which were built by Mughal emperor Jahangir in 1620 A.D. Later, a beautiful garden next to this spring, was laid out by his son Shah Jahan. This spring is known to never dry up or overflow. Verinag Spring is also the major source of river Jhelum. Verinag Spring and Mughal Arcade surrounding it is officially recognized by Archaeological Survey of India as a Monument of National Importance. Pahalgam (Hindustani pronunciation: [pɛhɛlɡaːm]), known as Pahalgom (Kashmiri pronunciation: [pəhəlʲɡoːm]; lit. 'village of shepherds' in Kashmiri)[14] is a town and a notified area committee, near Anantnag city in the Anantnag district of the Indian-administered union territory of Jammu and Kashmir.[15][16][17][18][19] It is a popular tourist destination and hill station. Its lush green meadows and pristine waters attract thousands of tourists from all over the world each year.[20] It is located 45 kilometres (28 mi) from Anantnag on the banks of Lidder River at an altitude of 7,200 feet (2,200 m). Pahalgam is the headquarters of one of the eleven tehsils of Anantnag district.

Pahalgam is associated with the annual pilgrimage to the shrine Amarnath Yatra. Chandanwari, located 16 kilometres (9.9 mi) from Pahalgam. The town is the starting point of the yatra that takes place every year in the months of July–August, receiving hundreds of thousands of tourists. Because of its religious significance and role as a base camp, the town attracts 70% of visitors to the valley. This flood of tourists overwhelms some of the local infrastructure, especially waste management in the town. This section is an excerpt from Sonamarg § Tourism.[edit]
Sonamarg provides trekking routes leading to Vishansar Lake, Krishansar Lake, Gangabal Lake and Gadsar Lake in the Himalayas, which are stocked with snowtrout and brown trout. The Sind River meanders here and abounds with trout and mahseer. Ponies can be hired for the trip up to Thajiwas glacier, a major attraction during the summer months. The Yatra to the nearby Amarnath Temple begins in Sonamarg.

Baltal, 15 km east of Sonamarg, is a valley that lies at the foot of the Zoji La pass. Trekkers can also reach the city of Leh—known as "the rooftop of the world"—by crossing over the Zoji La.

The Jammu and Kashmir tourism department organizes river rafting tournaments at Sonamarg throughout the year, which has recently seen the participation of teams from abroad. Verinag (/ˈveɪriːnɑːɡ/ is a town named after and famous for the Verinag spring and Mughal garden, near Anantnag city in Anantnag district of the union territory of Jammu and Kashmir, India. It is a notified area committee with tehsil status (Shahabad Bala Verinag) and is about 26 kilometers away from Anantnag and approximately 78 kilometres south-east from Srinagar which is the summer capital of the union territory of Jammu and Kashmir. Verinag is also the first tourist spot of Kashmir Valley when travelling by road from Jammu, the winter capital of the union territory of Jammu and Kashmir towards Srinagar. There is an octagonal stone basin at Verinag Spring and an arcade surrounding it which were built by Mughal emperor Jahangir in 1620 A.D. Later, a beautiful garden next to this spring, was laid out by his son Shah Jahan. This spring is known to never dry up or overflow. Verinag Spring is also the major source of river Jhelum. Verinag Spring and Mughal Arcade surrounding it is officially recognized by Archaeological Survey of India as a Monument of National Importance. Pahalgam (Hindustani pronunciation: [pɛhɛlɡaːm]), known as Pahalgom (Kashmiri pronunciation: [pəhəlʲɡoːm]; lit. 'village of shepherds' in Kashmiri)[14] is a town and a notified area committee, near Anantnag city in the Anantnag district of the Indian-administered union territory of Jammu and Kashmir.[15][16][17][18][19] It is a popular tourist destination and hill station. Its lush green meadows and pristine waters attract thousands of tourists from all over the world each year.[20] It is located 45 kilometres (28 mi) from Anantnag on the banks of Lidder River at an altitude of 7,200 feet (2,200 m). Pahalgam is the headquarters of one of the eleven tehsils of Anantnag district.

Pahalgam is associated with the annual pilgrimage to the shrine Amarnath Yatra. Chandanwari, located 16 kilometres (9.9 mi) from Pahalgam. The town is the starting point of the yatra that takes place every year in the months of July–August, receiving hundreds of thousands of tourists. Because of its religious significance and role as a base camp, the town attracts 70% of visitors to the valley. This flood of tourists overwhelms some of the local infrastructure, especially waste management in the town. This section is an excerpt from Sonamarg § Tourism.[edit]
Sonamarg provides trekking routes leading to Vishansar Lake, Krishansar Lake, Gangabal Lake and Gadsar Lake in the Himalayas, which are stocked with snowtrout and brown trout. The Sind River meanders here and abounds with trout and mahseer. Ponies can be hired for the trip up to Thajiwas glacier, a major attraction during the summer months. The Yatra to the nearby Amarnath Temple begins in Sonamarg.

Baltal, 15 km east of Sonamarg, is a valley that lies at the foot of the Zoji La pass. Trekkers can also reach the city of Leh—known as "the rooftop of the world"—by crossing over the Zoji La.

The Jammu and Kashmir tourism department organizes river rafting tournaments at Sonamarg throughout the year, which has recently seen the participation of teams from abroad. Verinag (/ˈveɪriːnɑːɡ/ is a town named after and famous for the Verinag spring and Mughal garden, near Anantnag city in Anantnag district of the union territory of Jammu and Kashmir, India. It is a notified area committee with tehsil status (Shahabad Bala Verinag) and is about 26 kilometers away from Anantnag and approximately 78 kilometres south-east from Srinagar which is the summer capital of the union territory of Jammu and Kashmir. Verinag is also the first tourist spot of Kashmir Valley when travelling by road from Jammu, the winter capital of the union territory of Jammu and Kashmir towards Srinagar. There is an octagonal stone basin at Verinag Spring and an arcade surrounding it which were built by Mughal emperor Jahangir in 1620 A.D. Later, a beautiful garden next to this spring, was laid out by his son Shah Jahan. This spring is known to never dry up or overflow. Verinag Spring is also the major source of river Jhelum. Verinag Spring and Mughal Arcade surrounding it is officially recognized by Archaeological Survey of India as a Monument of National Importance. Pahalgam (Hindustani pronunciation: [pɛhɛlɡaːm]), known as Pahalgom (Kashmiri pronunciation: [pəhəlʲɡoːm]; lit. 'village of shepherds' in Kashmiri)[14] is a town and a notified area committee, near Anantnag city in the Anantnag district of the Indian-administered union territory of Jammu and Kashmir.[15][16][17][18][19] It is a popular tourist destination and hill station. Its lush green meadows and pristine waters attract thousands of tourists from all over the world each year.[20] It is located 45 kilometres (28 mi) from Anantnag on the banks of Lidder River at an altitude of 7,200 feet (2,200 m). Pahalgam is the headquarters of one of the eleven tehsils of Anantnag district.

Pahalgam is associated with the annual pilgrimage to the shrine Amarnath Yatra. Chandanwari, located 16 kilometres (9.9 mi) from Pahalgam. The town is the starting point of the yatra that takes place every year in the months of July–August, receiving hundreds of thousands of tourists. Because of its religious significance and role as a base camp, the town attracts 70% of visitors to the valley. This flood of tourists overwhelms some of the local infrastructure, especially waste management in the town. This section is an excerpt from Sonamarg § Tourism.[edit]
Sonamarg provides trekking routes leading to Vishansar Lake, Krishansar Lake, Gangabal Lake and Gadsar Lake in the Himalayas, which are stocked with snowtrout and brown trout. The Sind River meanders here and abounds with trout and mahseer. Ponies can be hired for the trip up to Thajiwas glacier, a major attraction during the summer months. The Yatra to the nearby Amarnath Temple begins in Sonamarg.

Baltal, 15 km east of Sonamarg, is a valley that lies at the foot of the Zoji La pass. Trekkers can also reach the city of Leh—known as "the rooftop of the world"—by crossing over the Zoji La.

The Jammu and Kashmir tourism department organizes river rafting tournaments at Sonamarg throughout the year, which has recently seen the participation of teams from abroad. Verinag (/ˈveɪriːnɑːɡ/ is a town named after and famous for the Verinag spring and Mughal garden, near Anantnag city in Anantnag district of the union territory of Jammu and Kashmir, India. It is a notified area committee with tehsil status (Shahabad Bala Verinag) and is about 26 kilometers away from Anantnag and approximately 78 kilometres south-east from Srinagar which is the summer capital of the union territory of Jammu and Kashmir. Verinag is also the first tourist spot of Kashmir Valley when travelling by road from Jammu, the winter capital of the union territory of Jammu and Kashmir towards Srinagar. There is an octagonal stone basin at Verinag Spring and an arcade surrounding it which were built by Mughal emperor Jahangir in 1620 A.D. Later, a beautiful garden next to this spring, was laid out by his son Shah Jahan. This spring is known to never dry up or overflow. Verinag Spring is also the major source of river Jhelum. Verinag Spring and Mughal Arcade surrounding it is officially recognized by Archaeological Survey of India as a Monument of National Importance. Pahalgam (Hindustani pronunciation: [pɛhɛlɡaːm]), known as Pahalgom (Kashmiri pronunciation: [pəhəlʲɡoːm]; lit. 'village of shepherds' in Kashmiri)[14] is a town and a notified area committee, near Anantnag city in the Anantnag district of the Indian-administered union territory of Jammu and Kashmir.[15][16][17][18][19] It is a popular tourist destination and hill station. Its lush green meadows and pristine waters attract thousands of tourists from all over the world each year.[20] It is located 45 kilometres (28 mi) from Anantnag on the banks of Lidder River at an altitude of 7,200 feet (2,200 m). Pahalgam is the headquarters of one of the eleven tehsils of Anantnag district.

Pahalgam is associated with the annual pilgrimage to the shrine Amarnath Yatra. Chandanwari, located 16 kilometres (9.9 mi) from Pahalgam. The town is the starting point of the yatra that takes place every year in the months of July–August, receiving hundreds of thousands of tourists. Because of its religious significance and role as a base camp, the town attracts 70% of visitors to the valley. This flood of tourists overwhelms some of the local infrastructure, especially waste management in the town. This section is an excerpt from Sonamarg § Tourism.[edit]
Sonamarg provides trekking routes leading to Vishansar Lake, Krishansar Lake, Gangabal Lake and Gadsar Lake in the Himalayas, which are stocked with snowtrout and brown trout. The Sind River meanders here and abounds with trout and mahseer. Ponies can be hired for the trip up to Thajiwas glacier, a major attraction during the summer months. The Yatra to the nearby Amarnath Temple begins in Sonamarg.

Baltal, 15 km east of Sonamarg, is a valley that lies at the foot of the Zoji La pass. Trekkers can also reach the city of Leh—known as "the rooftop of the world"—by crossing over the Zoji La.

The Jammu and Kashmir tourism department organizes river rafting tournaments at Sonamarg throughout the year, which has recently seen the participation of teams from abroad. Verinag (/ˈveɪriːnɑːɡ/ is a town named after and famous for the Verinag spring and Mughal garden, near Anantnag city in Anantnag district of the union territory of Jammu and Kashmir, India. It is a notified area committee with tehsil status (Shahabad Bala Verinag) and is about 26 kilometers away from Anantnag and approximately 78 kilometres south-east from Srinagar which is the summer capital of the union territory of Jammu and Kashmir. Verinag is also the first tourist spot of Kashmir Valley when travelling by road from Jammu, the winter capital of the union territory of Jammu and Kashmir towards Srinagar. There is an octagonal stone basin at Verinag Spring and an arcade surrounding it which were built by Mughal emperor Jahangir in 1620 A.D. Later, a beautiful garden next to this spring, was laid out by his son Shah Jahan. This spring is known to never dry up or overflow. Verinag Spring is also the major source of river Jhelum. Verinag Spring and Mughal Arcade surrounding it is officially recognized by Archaeological Survey of India as a Monument of National Importance.</p>

	
</body>
</html>