<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
<img src="Images/img10.jpg">


	<style>
body {
  background-color: lightblue;
}

h1 {
  color: maroon;
  margin-left: 40px;
} 
</style>
</head>


	<title></title>

</head>
<body>
	
	<h1>Uttrakhand</h1>
	<p>Jammu & Kashmir, a piece of heaven on earth, is the 19th largest state in India and it is located mostly all in the Himalayan mountains. It is also the only state in India with a Muslim-majority population. J&K consists of three main regions – Jammu, the Kashmir Valley and Ladakh. Between the three, the state offers beautiful verdant mountains and valleys, religious shrines and remote mountains. The people here are warm and hospitable, and they will welcome you into their land and homes easily. Each of these regions has its own culture, and this is evident in their daily lives and also their lifestyle. Whatever your reason for visiting J&K, whether it is to enjoy the beauty, or test your limits while trekking the mountains, or simply to discover serenity and peace, J&K will offer you several reasons to keep coming back for more. 
Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.
Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.
Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.
Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.
Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.
Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.</p>
	<p>A land of myths and mountains, Devbhoomi Uttarakhand, is one of the most beautiful states of India. Snow-capped Himalayan peaks, serpentine rivers, revered temples, quaint villages, vibrant culture, and World Heritage Sites, Uttarakhand's sheer natural beauty and diversity beckon travelers from across the world. 

Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.</p>
<p>The Alaknanda River, which originates in the eastern slopes of glacier fields of Chaukhamba, is joined by the Saraswathi River near Mana (that originates on the south from the international border), and then flows in front of the Badrinath temple, one of the most revered Hindu shrines. It then meets the Dhauli Ganges River, whose origin is from the Niti Pass, after traveling a distance of 25 km (15.5 mi) from its source to form the Vishnu Prayag (30°33′45″N 79°34′31″E). This stretch of the Alaknanda River is called the Vishnu Ganges. Legend narrates the worship offered by sage Narada to god Vishnu at this confluence. An octagonal shaped temple – located near the confluence – dated to 1889, is credited to Maharani of Indore – Ahalyabai. Though originally built to install a Shiva linga, it now houses a Vishnu image. A stairway from this temple leads to the Vishnu kund (kund means pool of water or lake) at the confluence, which is seen in a tranquil state.</p>
<p>Nand Prayag (30°19′56″N 79°18′55″E) is the second prayag in the cascade sequence of the confluences where the Nandakini River joins the main Alaknanda River. According to one tale, a noble King Nanda performed Yagnya (fire-sacrifice) and sought blessings of God. 
Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.
Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.
Be it river rafting in the Ganges, trekking to some of the fascinating peaks, skiing through some of the picturesque slopes, enjoying a cable-car ride, or soaking in the mesmerising views of the Himalayas, Uttarakhand is a dream destination for all. Here are the top destinations to travel to in Uttarakhand. Haridwar Kumbh Mela (fair) is a major tourist attraction to the state. Haridwar is one of the four places in India where this takes place. Haridwar also has its big annual fair in the form of Magh Mela in January–February which turns into a bigger event every 6 years in the form of Ardh Magh Mela. Nanda Devi Mela and Nanda Devi Raj Yatra are great festivals of Uttarakhand, famous in all northern India. Nanda Devi Mela and Raj Yatra are the festivals of the goddess Nanda Devi, the bless-giving goddess.[12] Kumaoni Holi a regional variant of the Hindu festival of Holi is also very well known. Panch Prayag (Sanskrit: पंच-प्रयाग) is an expression in Hindu religious ethos, specifically used to connote the five sacred river confluences in the Garhwal Himalayas in the state of Uttarakhand, India. The five prayags – prayag meaning "confluence" in Sanskrit – also termed as "Prayag pentad", namely the five river confluences, are Vishnu Prayag, Nand Prayag, Karn prayag, Rudra Prayag and Dev Prayag, in the descending flow sequence of their occurrence.Hence, the confluence is named after him. The other version of the legend states that the confluence derives its name from the Yadava king Nanda, the foster-father of god Krishna. According to the legend, Vishnu granted a boon of the birth of a son to Nanda and his wife Yashoda and also the same boon to Devaki, wife of Vasudeva. Placed in a dilemma, since both were his disciples, he ensured that Krishna, an incarnation of Vishnu, was born to Devaki and Vasudeva but was fostered by Yashoda and Nanda.[17][18] There is temple for Gopal, a form of Krishna, here.[19] The legends also narrate that sage Kanva did penance here and also that wedding of King Dushyanta and Shakuntala took place at this venue.</p>

</body>
</html>