<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

<img src="Images/Img8.jpg">

	<style>
body {
  background-color: lightblue;
}

h1 {
  color: maroon;
  margin-left: 40px;
} 
</style>
</head>


	<title></title>

</head>
<body>
	
	<h1>Goa</h1>
	<p>Goa is a state in western India with coastlines stretching along the Arabian Sea. Its long history as a Portuguese colony prior to 1961 is evident in its preserved 17th-century churches and the area’s tropical spice plantations. Goa is also known for its beaches, ranging from popular stretches at Baga and Palolem to those in laid-back fishing villages such as Agonda. The Administrative head of the Department is Shri. Ravi Dhawan, IAS, Secretary Tourism. The Department has zonal office in North Goa at Headquarters, Panaji and in South Goa at Margao.

The Current Director of Tourism is Shri Nikhil Desai, IAS.
The Public Grievances Officer is Dy. Director (Administration).

The Tourist Information Centres/Counters are located within the State and in Mumbai (temporarily closed). The Zonal Officers are primarily responsible for monitoring the Registration of Tourist Trade under the Tourist Trade Act, 1982.  Evidence from rock art engravings suggests that the region that is currently called Goa has been inhabited by humans even during the Paleolithic Age. From the third century onwards, it has been under the reign of different dynasties and powers, such as the Mouryas, Bhojas, Kadambas, Delhi Sultanate, and Adil Shahis, to name a few. In the 16th century, Goa came under the rule of the Portuguese. The period of Portuguese colonialism, which lasted for about 450 years, played a pivotal role in shaping the modern history and culture of Goa. The Portuguese rule ended in 1961 when Goa was annexed to the Republic of India through Operation Vijay, the armed action carried out by the Indian Armed Forces. Although initially organized as a Union Territory, Goa was declared as the 25th state of India in 1987.  Goa is a state in the Konkan Region aka Konkan Coast which forms the western coastline of India. It shares its border with two other Indian states, namely Karnataka on the east and the south and Maharashtra on the north, while the western side is bordered by the majestic Arabian Sea. There are seven major rivers running through the state of which Zuari, Mandovi and Chapora are the most famous ones. The entire state is divided into two districts – North Goa and South Goa. While the northern part is famous as a partying hub, the southern part is ideal for laid-back beach vacations.

Due to its proximity to the coastal line, the region has a tropical monsoon climate marked by heat and humidity. The best time to visit Goa is from October to February. Summers are pretty harsh across the region and hence a trip to Goa during summers (March to June) is best avoided. 
Beaches: Baga, Calangute, Candolim, Vagator, Anjuna, Palolem, Butterfly, Colva, and Ashwem are the most-visited beaches in Goa. For those who want to enjoy some tranquil moments, there are less-crowded beaches in Goa that include Arambol, Mandrem, Morjim, Sinquerim, Cavelossim, and Agonda.
Forts: Fort Aguada, Chapora Fort, Tiracol Fort, Reis Magos Fort, Corjuem Fort, Cabo de Rama Fort, and Mormugao Fort are the most famous forts in Goa.
Churches: Basilica of Bom Jesus, Se Cathedral de Santa Catarina, Saint Catherine’s Chapel, Church of St. Francis of Assisi, Church of Our Lady of the Rosary, Church of Saint Augustine, Church of Saint Cajetan, Church of Our Lady of Immaculate Conception, Alex Church, Mae De Deus Church, Three Kings Chapel, Nossa Senhora de Penha de Franca, and Santa Cruz Church are among the top churches to visit in Goa.
Temples: Mangeshi Temple, Shanta Durga Temple, Mahadev Temple, Chandreshwar Bhoothnath Temple, Brahma Temple, Mahalasa Narayani Temple, Mahalaxmi Temple, Saptakoteshwar Temple, and Kamakshi Temple are some of the well-known temples in Goa.
Museums: Museum of Goa, Houses of Goa Museum, Goa Science Center, Museum of Christian Art, Wax Museum, Big Foot Cross Museum, Indian Naval Aviation Museum, and Goa Chitra Museum are the must-visit museums in Goa for history buffs.
Waterfalls: Dudhsagar Waterfalls, Hivre Waterfalls, Tambadi Surla Waterfalls, Arvalem Waterfalls, Kuskem Waterfalls, and Charavne Waterfalls are the most spectacular waterfalls in Goa.
National Parks and Wildlife Sanctuaries: Mhadei Wildlife Sanctuary, Bhagwan Mahaveer Sanctuary, Dr. Salim Ali Bird Sanctuary, Bondla Wildlife Sanctuary, Netravali Wildlife Sanctuary, and Cotigao Wildlife Sanctuary are the best wildlife sanctuaries and biodiversity spots in Goa.
Lakes: Mayem Lake, Carambolim Lake, Netravali Lake, Batim Lake, Ambulor Lake, Sarzora Lake, and Arambol Sweet Water Lake are among the top lakes to visit in Goa.</p>

<p>The Tourist Information Centres/Counters are located within the State and in Mumbai (temporarily closed). The Zonal Officers are primarily responsible for monitoring the Registration of Tourist Trade under the Tourist Trade Act, 1982.  Evidence from rock art engravings suggests that the region that is currently called Goa has been inhabited by humans even during the Paleolithic Age. From the third century onwards, it has been under the reign of different dynasties and powers, such as the Mouryas, Bhojas, Kadambas, Delhi Sultanate, and Adil Shahis, to name a few. In the 16th century, Goa came under the rule of the Portuguese. The period of Portuguese colonialism, which lasted for about 450 years, played a pivotal role in shaping the modern history and culture of Goa. The Portuguese rule ended in 1961 when Goa was annexed to the Republic of India through Operation Vijay, the armed action carried out by the Indian Armed Forces. Although initially organized as a Union Territory, Goa was declared as the 25th state of India in 1987.  Goa is a state in the Konkan Region aka Konkan Coast which forms the western coastline of India. It shares its border with two other Indian states, namely Karnataka on the east and the south and Maharashtra on the north, while the western side is bordered by the majestic Arabian Sea. There are seven major rivers running through the state of which Zuari, Mandovi and Chapora are the most famous ones. The entire state is divided into two districts – North Goa and South Goa. While the northern part is famous as a partying hub, the southern part is ideal for laid-back beach vacations.

Due to its proximity to the coastal line, the region has a tropical monsoon climate marked by heat and humidity. The best time to visit Goa is from October to February. Summers are pretty harsh across the region and hence a trip to Goa during summers (March to June) is best avoided. 
Beaches: Baga, Calangute, Candolim, Vagator, Anjuna, Palolem, Butterfly, Colva, and Ashwem are the most-visited beaches in Goa. For those who want to enjoy some tranquil moments, there are less-crowded beaches in Goa that include Arambol, Mandrem, Morjim, Sinquerim, Cavelossim, and Agonda.
Forts: Fort Aguada, Chapora Fort, Tiracol Fort, Reis Magos Fort, Corjuem Fort, Cabo de Rama Fort, and Mormugao Fort are the most famous forts in Goa.
Churches: Basilica of Bom Jesus, Se Cathedral de Santa Catarina, Saint Catherine’s Chapel, Church of St. Francis of Assisi, Church of Our Lady of the Rosary, Church of Saint Augustine, Church of Saint Cajetan, Church of Our Lady of Immaculate Conception, Alex Church, Mae De Deus Church, Three Kings Chapel, Nossa Senhora de Penha de Franca, and Santa Cruz Church are among the top churches to visit in Goa.
Temples: Mangeshi Temple, Shanta Durga Temple, Mahadev Temple, Chandreshwar Bhoothnath Temple, Brahma Temple, Mahalasa Narayani Temple, Mahalaxmi Temple, Saptakoteshwar Temple, and Kamakshi Temple are some of the well-known temples in Goa.
Museums: Museum of Goa, Houses of Goa Museum, Goa Science Center, Museum of Christian Art, Wax Museum, Big Foot Cross Museum, Indian Naval Aviation Museum, and Goa Chitra Museum are the must-visit museums in Goa for history buffs.
Waterfalls: Dudhsagar Waterfalls, Hivre Waterfalls, Tambadi Surla Waterfalls, Arvalem Waterfalls, Kuskem Waterfalls, and Charavne Waterfalls are the most spectacular waterfalls in Goa.
National Parks and Wildlife Sanctuaries: Mhadei Wildlife Sanctuary, Bhagwan Mahaveer Sanctuary, Dr. Salim Ali Bird Sanctuary, Bondla Wildlife Sanctuary, Netravali Wildlife Sanctuary, and Cotigao Wildlife Sanctuary are the best wildlife sanctuaries and biodiversity spots in Goa.
Lakes: Mayem Lake, Carambolim Lake, Netravali Lake, Batim Lake, Ambulor Lake, Sarzora Lake, and Arambol Sweet Water Lake are among the top lakes to visit in Goa. The Tourist Information Centres/Counters are located within the State and in Mumbai (temporarily closed). The Zonal Officers are primarily responsible for monitoring the Registration of Tourist Trade under the Tourist Trade Act, 1982.  Evidence from rock art engravings suggests that the region that is currently called Goa has been inhabited by humans even during the Paleolithic Age. From the third century onwards, it has been under the reign of different dynasties and powers, such as the Mouryas, Bhojas, Kadambas, Delhi Sultanate, and Adil Shahis, to name a few. In the 16th century, Goa came under the rule of the Portuguese. The period of Portuguese colonialism, which lasted for about 450 years, played a pivotal role in shaping the modern history and culture of Goa. The Portuguese rule ended in 1961 when Goa was annexed to the Republic of India through Operation Vijay, the armed action carried out by the Indian Armed Forces. Although initially organized as a Union Territory, Goa was declared as the 25th state of India in 1987.  Goa is a state in the Konkan Region aka Konkan Coast which forms the western coastline of India. It shares its border with two other Indian states, namely Karnataka on the east and the south and Maharashtra on the north, while the western side is bordered by the majestic Arabian Sea. There are seven major rivers running through the state of which Zuari, Mandovi and Chapora are the most famous ones. The entire state is divided into two districts – North Goa and South Goa. While the northern part is famous as a partying hub, the southern part is ideal for laid-back beach vacations.

Due to its proximity to the coastal line, the region has a tropical monsoon climate marked by heat and humidity. The best time to visit Goa is from October to February. Summers are pretty harsh across the region and hence a trip to Goa during summers (March to June) is best avoided. 
Beaches: Baga, Calangute, Candolim, Vagator, Anjuna, Palolem, Butterfly, Colva, and Ashwem are the most-visited beaches in Goa. For those who want to enjoy some tranquil moments, there are less-crowded beaches in Goa that include Arambol, Mandrem, Morjim, Sinquerim, Cavelossim, and Agonda.
Forts: Fort Aguada, Chapora Fort, Tiracol Fort, Reis Magos Fort, Corjuem Fort, Cabo de Rama Fort, and Mormugao Fort are the most famous forts in Goa.
Churches: Basilica of Bom Jesus, Se Cathedral de Santa Catarina, Saint Catherine’s Chapel, Church of St. Francis of Assisi, Church of Our Lady of the Rosary, Church of Saint Augustine, Church of Saint Cajetan, Church of Our Lady of Immaculate Conception, Alex Church, Mae De Deus Church, Three Kings Chapel, Nossa Senhora de Penha de Franca, and Santa Cruz Church are among the top churches to visit in Goa.
Temples: Mangeshi Temple, Shanta Durga Temple, Mahadev Temple, Chandreshwar Bhoothnath Temple, Brahma Temple, Mahalasa Narayani Temple, Mahalaxmi Temple, Saptakoteshwar Temple, and Kamakshi Temple are some of the well-known temples in Goa.
Museums: Museum of Goa, Houses of Goa Museum, Goa Science Center, Museum of Christian Art, Wax Museum, Big Foot Cross Museum, Indian Naval Aviation Museum, and Goa Chitra Museum are the must-visit museums in Goa for history buffs.
Waterfalls: Dudhsagar Waterfalls, Hivre Waterfalls, Tambadi Surla Waterfalls, Arvalem Waterfalls, Kuskem Waterfalls, and Charavne Waterfalls are the most spectacular waterfalls in Goa.
National Parks and Wildlife Sanctuaries: Mhadei Wildlife Sanctuary, Bhagwan Mahaveer Sanctuary, Dr. Salim Ali Bird Sanctuary, Bondla Wildlife Sanctuary, Netravali Wildlife Sanctuary, and Cotigao Wildlife Sanctuary are the best wildlife sanctuaries and biodiversity spots in Goa.
Lakes: Mayem Lake, Carambolim Lake, Netravali Lake, Batim Lake, Ambulor Lake, Sarzora Lake, and Arambol Sweet Water Lake are among the top lakes to visit in Goa.</p>
	<p>Goa is a state in western India with coastlines stretching along the Arabian Sea. Its long history as a Portuguese colony prior to 1961 is evident in its preserved 17th-century churches and the area’s tropical spice plantations. Goa is also known for its beaches, ranging from popular stretches at Baga and Palolem to those in laid-back fishing villages such as Agonda. The Administrative head of the Department is Shri. Ravi Dhawan, IAS, Secretary Tourism. The Department has zonal office in North Goa at Headquarters, Panaji and in South Goa at Margao.

The Current Director of Tourism is Shri Nikhil Desai, IAS.
The Public Grievances Officer is Dy. Director (Administration).

The Tourist Information Centres/Counters are located within the State and in Mumbai (temporarily closed). The Zonal Officers are primarily responsible for monitoring the Registration of Tourist Trade under the Tourist Trade Act, 1982.  Evidence from rock art engravings suggests that the region that is currently called Goa has been inhabited by humans even during the Paleolithic Age. From the third century onwards, it has been under the reign of different dynasties and powers, such as the Mouryas, Bhojas, Kadambas, Delhi Sultanate, and Adil Shahis, to name a few. In the 16th century, Goa came under the rule of the Portuguese. The period of Portuguese colonialism, which lasted for about 450 years, played a pivotal role in shaping the modern history and culture of Goa. The Portuguese rule ended in 1961 when Goa was annexed to the Republic of India through Operation Vijay, the armed action carried out by the Indian Armed Forces. Although initially organized as a Union Territory, Goa was declared as the 25th state of India in 1987.  Goa is a state in the Konkan Region aka Konkan Coast which forms the western coastline of India. It shares its border with two other Indian states, namely Karnataka on the east and the south and Maharashtra on the north, while the western side is bordered by the majestic Arabian Sea. There are seven major rivers running through the state of which Zuari, Mandovi and Chapora are the most famous ones. The entire state is divided into two districts – North Goa and South Goa. While the northern part is famous as a partying hub, the southern part is ideal for laid-back beach vacations.

Due to its proximity to the coastal line, the region has a tropical monsoon climate marked by heat and humidity. The best time to visit Goa is from October to February. Summers are pretty harsh across the region and hence a trip to Goa during summers (March to June) is best avoided. 
Beaches: Baga, Calangute, Candolim, Vagator, Anjuna, Palolem, Butterfly, Colva, and Ashwem are the most-visited beaches in Goa. For those who want to enjoy some tranquil moments, there are less-crowded beaches in Goa that include Arambol, Mandrem, Morjim, Sinquerim, Cavelossim, and Agonda.
Forts: Fort Aguada, Chapora Fort, Tiracol Fort, Reis Magos Fort, Corjuem Fort, Cabo de Rama Fort, and Mormugao Fort are the most famous forts in Goa.
Churches: Basilica of Bom Jesus, Se Cathedral de Santa Catarina, Saint Catherine’s Chapel, Church of St. Francis of Assisi, Church of Our Lady of the Rosary, Church of Saint Augustine, Church of Saint Cajetan, Church of Our Lady of Immaculate Conception, Alex Church, Mae De Deus Church, Three Kings Chapel, Nossa Senhora de Penha de Franca, and Santa Cruz Church are among the top churches to visit in Goa.
Temples: Mangeshi Temple, Shanta Durga Temple, Mahadev Temple, Chandreshwar Bhoothnath Temple, Brahma Temple, Mahalasa Narayani Temple, Mahalaxmi Temple, Saptakoteshwar Temple, and Kamakshi Temple are some of the well-known temples in Goa.
Museums: Museum of Goa, Houses of Goa Museum, Goa Science Center, Museum of Christian Art, Wax Museum, Big Foot Cross Museum, Indian Naval Aviation Museum, and Goa Chitra Museum are the must-visit museums in Goa for history buffs.
Waterfalls: Dudhsagar Waterfalls, Hivre Waterfalls, Tambadi Surla Waterfalls, Arvalem Waterfalls, Kuskem Waterfalls, and Charavne Waterfalls are the most spectacular waterfalls in Goa.
National Parks and Wildlife Sanctuaries: Mhadei Wildlife Sanctuary, Bhagwan Mahaveer Sanctuary, Dr. Salim Ali Bird Sanctuary, Bondla Wildlife Sanctuary, Netravali Wildlife Sanctuary, and Cotigao Wildlife Sanctuary are the best wildlife sanctuaries and biodiversity spots in Goa.
Lakes: Mayem Lake, Carambolim Lake, Netravali Lake, Batim Lake, Ambulor Lake, Sarzora Lake, and Arambol Sweet Water Lake are among the top lakes to visit in Goa.</p>
</body>
</html>